
import React, { useState, useEffect } from 'react';
import { BookStructure } from '../types';
import { Download, ChevronRight, Book, Image as ImageIcon, ShieldCheck, Copy, Check, FileText, ExternalLink } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface BookPreviewProps {
  book: BookStructure;
  onExport: () => void;
  onReset: () => void;
}

/**
 * Renders a single section with interactive citations.
 */
const SectionRenderer: React.FC<{ section: any, chapterIdx: number, sectionIdx: number, isRtl: boolean }> = ({ section, chapterIdx, sectionIdx, isRtl }) => {
  const [highlightedNote, setHighlightedNote] = useState<number | null>(null);
  
  // Split content and notes using the hidden separator from geminiService
  const separator = "<!--NOTES_SECTION_START-->";
  const [markdownContent, notesRaw] = section.content.split(separator);
  
  // Parse the raw notes string into structured data
  const notes = React.useMemo(() => {
    if (!notesRaw) return [];
    // Remove "**Notes:**" header if present
    const cleanNotes = notesRaw.replace(/\*\*Notes:\*\*\s*/, '').trim();
    // Parse lines: "1. content"
    return cleanNotes.split('\n').map(line => {
      const match = line.match(/^(\d+)\.\s+(.*)$/);
      if (match) return { id: parseInt(match[1]), text: match[2] };
      return null;
    }).filter(Boolean);
  }, [notesRaw]);

  // Handle citation click: scroll and highlight
  const handleCitationClick = (e: React.MouseEvent, noteId: number) => {
    e.preventDefault();
    setHighlightedNote(noteId);
    
    // Find the specific note element for this section
    const noteEl = document.getElementById(`note-${chapterIdx}-${sectionIdx}-${noteId}`);
    if (noteEl) {
      noteEl.scrollIntoView({ behavior: 'smooth', block: 'center' });
      // Remove highlight after animation
      setTimeout(() => setHighlightedNote(null), 3000);
    }
  };

  return (
    <div className="prose prose-lg prose-headings:font-serif prose-headings:text-islamic-green max-w-none mb-12">
      <h3 className={`text-2xl font-bold mb-4 ${isRtl ? 'font-arabic' : ''}`}>{section.title}</h3>
      <div className={`text-gray-700 leading-relaxed font-serif ${isRtl ? 'text-right font-arabic text-xl leading-loose' : ''}`}>
        <ReactMarkdown
           components={{
             a: ({node, href, children, ...props}) => {
               // Check if it's our citation link generated by geminiService
               // href format: #citation-cIdx-sIdx-noteId
               const match = href?.match(/#citation-(\d+)-(\d+)-(\d+)/);
               if (match) {
                 const [_, c, s, n] = match;
                 // Verify it matches current section to prevent cross-section jumps
                 if (parseInt(c) === chapterIdx && parseInt(s) === sectionIdx) {
                    return (
                        <a 
                          href={href} 
                          onClick={(e) => handleCitationClick(e, parseInt(n))}
                          className="text-islamic-gold no-underline font-bold text-xs align-super hover:underline cursor-pointer px-0.5 bg-yellow-50 rounded mx-0.5 border border-yellow-100"
                          title="View Citation"
                        >
                           {children}
                        </a>
                    )
                 }
               }
               // Default link behavior
               return <a href={href} {...props} className="text-blue-600 hover:underline">{children}</a>
             }
           }}
        >
          {markdownContent}
        </ReactMarkdown>
      </div>

      {notes.length > 0 && (
         <div className="mt-8 pt-6 border-t border-gray-200 bg-gray-50/50 rounded-lg p-6">
           <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-2">
             <Book size={12} />
             References & Notes
           </h4>
           <ol className="space-y-3" dir={isRtl ? "rtl" : "ltr"}>
             {notes.map((note: any) => (
               <li 
                 key={note.id} 
                 id={`note-${chapterIdx}-${sectionIdx}-${note.id}`}
                 className={`text-sm text-gray-600 transition-all duration-1000 p-3 rounded-md border ${
                   highlightedNote === note.id 
                     ? 'bg-amber-50 border-amber-200 shadow-sm text-gray-900 scale-[1.01]' 
                     : 'border-transparent hover:bg-white hover:border-gray-200'
                 }`}
               >
                 <span className="font-bold text-islamic-green mr-2 inline-block min-w-[1.5rem]">{note.id}.</span>
                 {note.text}
               </li>
             ))}
           </ol>
         </div>
       )}
    </div>
  )
};

const BookPreview: React.FC<BookPreviewProps> = ({ book, onExport, onReset }) => {
  const [activeChapterIndex, setActiveChapterIndex] = useState(0);
  const [copied, setCopied] = useState(false);

  const activeChapter = book.chapters[activeChapterIndex];
  const isRtl = book.language?.toLowerCase().includes('arab');

  const handleCopy = async () => {
    try {
      let textContent = `# ${book.title}\n${book.subtitle}\n\nBy ${book.author}\n\n`;
      textContent += `## Abstract\n${book.abstract}\n\n`;
      
      book.chapters.forEach((chapter, i) => {
        textContent += `## Chapter ${i + 1}: ${chapter.title}\n\n`;
        chapter.sections.forEach(section => {
          // Clean the separators for raw copy
          const cleanContent = section.content.replace('<!--NOTES_SECTION_START-->', '');
          textContent += `### ${section.title}\n${cleanContent}\n\n`;
        });
      });

      textContent += `## References\n`;
      book.references.forEach(ref => textContent += `- ${ref}\n`);

      await navigator.clipboard.writeText(textContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handleDownloadRIS = () => {
    // Basic heuristic to convert free-text references to RIS
    const risContent = book.references.map((ref, i) => {
      // If reference contains a comma, we attempt to split Author, Title. 
      // Otherwise we put everything in Title.
      // This is a "Best Effort" approach for AI generated text.
      const parts = ref.split(',');
      let title = ref;
      let author = "";
      
      if (parts.length > 1) {
          author = parts[0].trim();
          title = parts.slice(1).join(',').trim();
      }

      return `TY  - BOOK
ID  - REF${i + 1}
TI  - ${title}
${author ? `AU  - ${author}` : ''}
PY  - ${new Date().getFullYear()}
N1  - Generated by Fiqh Book Crafting AI
ER  -`;
    }).join('\n\n');

    const blob = new Blob([risContent], { type: 'application/x-research-info-systems' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${book.title.replace(/[\s\W]+/g, "_")}_references.ris`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-screen max-h-screen bg-gray-100 overflow-hidden">
      {/* Top Bar */}
      <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between shadow-sm z-20">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-islamic-green rounded text-white">
            <Book size={20} />
          </div>
          <div>
            <h1 className="text-lg font-serif font-bold text-gray-900 leading-tight">{book.title}</h1>
            <p className="text-xs text-gray-500 uppercase tracking-wider">{book.subtitle}</p>
          </div>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={onReset}
            className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900"
          >
            Create New
          </button>
          
          <button
            onClick={handleCopy}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium shadow-sm transition-all ${
              copied 
                ? 'bg-green-100 text-green-700 border border-green-200' 
                : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
            }`}
            title="Copy full book text"
          >
            {copied ? <Check size={18} /> : <Copy size={18} />}
            {copied ? 'Copied!' : 'Copy Text'}
          </button>

          <button
            onClick={onExport}
            className="flex items-center gap-2 px-5 py-2 bg-islamic-gold hover:bg-amber-600 text-white rounded-lg font-medium shadow-md transition-colors"
          >
            <Download size={18} />
            Export Word
          </button>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar - Table of Contents */}
        <aside className="w-80 bg-white border-r border-gray-200 overflow-y-auto hidden md:block flex-shrink-0">
          <div className="p-6">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Table of Contents</h3>
            <div className="space-y-1">
              {book.chapters.map((chapter, idx) => (
                <button
                  key={idx}
                  onClick={() => setActiveChapterIndex(idx)}
                  className={`w-full text-left px-3 py-2 rounded-md text-sm transition-colors flex items-center justify-between group ${
                    activeChapterIndex === idx
                      ? 'bg-islamic-green/10 text-islamic-green font-semibold'
                      : 'text-gray-600 hover:bg-gray-50'
                  }`}
                  dir={isRtl ? "rtl" : "ltr"}
                >
                  <span className="truncate">{chapter.title}</span>
                  {activeChapterIndex === idx && <ChevronRight size={14} className={isRtl ? "rotate-180" : ""} />}
                </button>
              ))}
            </div>
            
            <div className="mt-8 pt-8 border-t border-gray-100">
               <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Bibliography</h3>
               <ul className="space-y-2 mb-6">
                 {book.references.map((ref, i) => (
                   <li key={i} className="text-xs text-gray-500 flex gap-2" dir={isRtl ? "rtl" : "ltr"}>
                     <span className="w-1.5 h-1.5 rounded-full bg-islamic-gold mt-1.5 shrink-0"></span>
                     {ref}
                   </li>
                 ))}
               </ul>

               {/* Citation Tools */}
               <div className="bg-gray-50 p-4 rounded-lg border border-gray-200 space-y-3">
                  <h4 className="text-xs font-bold text-gray-500 uppercase">Citation Tools</h4>
                  <button 
                    onClick={handleDownloadRIS}
                    className="w-full flex items-center justify-center gap-2 text-xs font-medium bg-white border border-gray-300 py-2 rounded hover:bg-gray-50 text-gray-700 transition"
                  >
                    <FileText size={14} />
                    Download .RIS File
                  </button>
                  <a 
                    href="https://www.mendeley.com/library/"
                    target="_blank"
                    rel="noreferrer"
                    className="w-full flex items-center justify-center gap-2 text-xs font-medium bg-[#980808] text-white py-2 rounded hover:bg-[#7d0606] transition"
                  >
                    <ExternalLink size={14} />
                    Verify on Mendeley
                  </a>
                  <p className="text-[10px] text-gray-400 text-center leading-tight">
                    Download .RIS then upload to Mendeley/Zotero to verify sources.
                  </p>
               </div>
            </div>
          </div>
        </aside>

        {/* Main Content - Reader */}
        <main className="flex-1 overflow-y-auto book-scroll bg-paper-cream relative p-8 md:p-12">
          <div className="max-w-3xl mx-auto space-y-12">
            
            {/* Chapter Header */}
            <div className="border-b-2 border-islamic-gold/20 pb-6" dir={isRtl ? "rtl" : "ltr"}>
              <span className="text-islamic-gold font-bold tracking-widest text-sm uppercase">Chapter {activeChapterIndex + 1}</span>
              <h2 className={`text-4xl font-serif font-bold text-gray-900 mt-2 ${isRtl ? 'font-arabic' : ''}`}>{activeChapter.title}</h2>
            </div>

            {/* Generated Illustration */}
            {book.coverImage && (
              <div className="my-8 p-2 bg-white rounded-xl border border-gray-200 shadow-sm">
                  <div className="flex items-center gap-3 mb-2 px-4 py-2">
                      <ImageIcon className="text-islamic-gold" size={20} />
                      <h4 className="font-bold text-gray-700 text-sm">Visual Illustration (AI Generated)</h4>
                  </div>
                  <div className="w-full overflow-hidden rounded-lg border border-gray-100">
                      <img 
                        src={book.coverImage} 
                        alt="AI Generated Book Illustration" 
                        className="w-full h-auto object-cover hover:scale-105 transition-transform duration-700"
                      />
                  </div>
                  <p className="text-center text-xs text-gray-400 mt-2 pb-1 italic">
                    Depiction relevant to: {book.title}
                  </p>
              </div>
            )}

            {/* Content Sections */}
            <div className="space-y-10" dir={isRtl ? "rtl" : "ltr"}>
              {activeChapter.sections.map((section, idx) => (
                <SectionRenderer 
                  key={idx} 
                  section={section} 
                  chapterIdx={activeChapterIndex} 
                  sectionIdx={idx} 
                  isRtl={!!isRtl} 
                />
              ))}
            </div>

            {/* Validation Badge */}
            <div className="flex justify-center mt-12 mb-6">
                <div className="inline-flex items-center gap-2 px-4 py-2 bg-green-50 text-green-700 rounded-full border border-green-200 text-sm">
                    <ShieldCheck size={16} />
                    <span>Validated against Authentic Sources</span>
                </div>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
};

export default BookPreview;
